### PR TITLE
Moved write_usage_metrics to Registry

### PR DESCRIPTION
**Pull request by JustAGod1**
Just want to have an ability to push usage metrics

### CODE REVIEW

**Comment by flyingmutant** [comment]
Please, don't mess the formatting.

Screenshot from 2023-08-01 23-44-45

**Comment by JustAGod1** [comment]
Yeah sorry, fixed.

**Review by alpinskiy — APPROVED** [review]

**Review by alpinskiy — CHANGES_REQUESTED** [review]
Need a lock

**Comment by JustAGod1** [comment]
lock has been added!

**Review by alpinskiy — APPROVED** [review]

**Pull request merged**
